server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: postgres
    password: postgres

  cloud:
    stream:
      pgq:
        default:
          consumer:
            consumer-id: test
        bindings:
          eventBusTest-in-0:
            consumer:
              consumer-id: hello
              tags: report
          event_bus-in-0:
            consumer:
              tags: fake
      bindings:
        eventBusTest-in-0:
          destination: event_bus_coop
          group: cid-event_bus-smart-home_test
        event_bus-in-0:
          destination: event_bus_coop
          group: cid-event_bus-smart-home
        event_bus-out-0:
          destination: event_bus_coop
      pollable-source: event_bus
