version: '3.9'

services:
  postgres_pqp:
    build:
      context: ./
      dockerfile: Dockerfile_postgres
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: smart_home
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
