version: '3.1'

services:
  postgres:
    image: postgres:12
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: smart_home
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
