FROM postgres:12

RUN apt update && apt -y upgrade
RUN apt -y install postgresql-12-pgq3 pgqd postgresql-server-dev-12 make git
RUN git clone https://github.com/pgq/pgq-coop.git
RUN cd pgq-coop && make install
RUN service pgqd start
